repos:

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    args: [--line-length=88, --safe]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: flake8
    args: [--max-line-length=88]

- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: pipenv run pytest
    pass_filenames: false
    language: system
